 # -------------------
# SERVER
# -------------------
spring.application.name=courseservice
server.port=8082

# -------------------
# JPA / HIBERNATE
# -------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# -------------------
# LOGGING
# -------------------
logging.level.com.myschool.coursesservice=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# -------------------
# FILE UPLOAD
# -------------------
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=${user.dir}/uploads/files/
course.image-dir=${user.dir}/uploads/courses/
