
# ===============================
# Application
# ===============================
spring.application.name=coursesservice
server.port=8082

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# Database (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/courses_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Logging (optionnel mais utile)
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG


# Taille max des fichiers
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Créer les dossiers au démarrage
file.upload-dir=${user.dir}/uploads/files/
course.image-dir=${user.dir}/uploads/courses/
