server.port=8761

spring.application.name=discovery

# Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false

# ===== PROMETHEUS & ACTUATOR =====
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true
